helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.7.2
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: true

resources:
- ./namespace.yaml
