apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: grafana-db
  namespace: infrastructure
spec:
  image: eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres:ubi8-14.4-0
  postgresVersion: 14
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: grafana-db
                    postgres-operator.crunchydata.com/instance-set: "00"
  backups:
    pgbackrest:
      image: eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgbackrest:ubi8-2.38-2
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            incremental: "0 1 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 5Gi
  monitoring:
    pgmonitor:
      exporter:
        image: eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-exporter:ubi8-5.1.2-0
  users:
    - name: grafana-db
      databases:
        - "grafana-db"