apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  baseImage: grafana/grafana:9.3.6
  deployment:
    replicas: 3
    envFrom:

    env:
    - name: GF_DATABASE_TYPE
      value: postgres
    - name: GF_DATABASE_HOST
      value: grafana-db-primary:5432
    - name: GF_DATABASE_NAME
      value: grafana-db
    - name: GF_DATABASE_USER
      valueFrom:
        secretKeyRef:
          key: "user"
          name: "grafana-db-pguser-grafana-db"
    - name: GF_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: "password"
          name: "grafana-db-pguser-grafana-db"
  
  ingress:
    enabled: False
  config:
    log:
      mode: "console"
      level: "warn"
    auth.anonymous:
      enabled: False
    database:
      ssl_mode: require
      type: postgres
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
