apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:none
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, argocd-admin, role:admin
  scopes: '[groups]'