helmCharts:
  - name: x509-certificate-exporter
    repo: https://charts.enix.io
    version: 3.2.0
    releaseName: x509-certificate-exporter
    namespace: infrastructure
    includeCRDs: true
    valuesFile: helm-values.yaml

resources:
  - ./grafana-dashboard/
