---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.2.3
  name: redis-operator
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-operator
      app.kubernetes.io/name: redis-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis-operator
        app.kubernetes.io/name: redis-operator
    spec:
      containers:
      - image: quay.io/spotahome/redis-operator:v1.2.3
        imagePullPolicy: IfNotPresent
        name: redis-operator
        ports:
        - containerPort: 9710
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      restartPolicy: Always
      serviceAccountName: redis-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.2.3
  name: redis-operator
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.2.3
  name: redis-operator
rules:
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers
  - redisfailovers/finalizers
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - persistentvolumeclaims
  - persistentvolumeclaims/finalizers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.2.3
  name: redis-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-operator
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: infrastructure
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.2.3
  name: redis-operator
  namespace: infrastructure
spec:
  ports:
  - name: metrics
    port: 9710
    protocol: TCP
  selector:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.2.3
  name: redis-operator
  namespace: infrastructure
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-operator
      app.kubernetes.io/name: redis-operator
