image: 
  tag: 2.0.1

ingress:
  enabled: false
  # annotations: 
  #   kubernetes.io/ingress.class: nginx
  # path: /
  # pathType: Prefix
  # hosts:
  #   - superset.example.com
  # tls:
  # - hosts:
  #   - superset.example.com
  #   secretName: wildcard.example.com

supersetNode:
  replicaCount: 1
  connections:
    # You need to change below configuration in case bringing own PostgresSQL instance and also set postgresql.enabled:false
    db_host: 'superset-db-pgbouncer'
    db_port: "5432"
    db_user: superset-db
    db_name: superset-db

extraEnvRaw:
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: superset-db-pguser-superset-db 
        key: password

configOverrides:
  feature_flags: |
    FEATURE_FLAGS = {
      'ENABLE_TEMPLATE_PROCESSING': True
    }

postgresql:
  enabled: false  ## Set to false if bringing your own PostgreSQL.

