apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: reef-beat@esolutions.ro
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory  # Use this when practicing
    privateKeySecretRef:
      name: cluster-issuer-letsencrypt                                # cert-manager will create this secret
    solvers:
    - dns01:
        cloudDNS:
          project: compelling-cat-212513                              # GCP project ID
          serviceAccountSecretRef:
            name: cert-manager-service-account                        # Make sure you have this secret containing the Service Account key
            key: cert-manager-service-account.json
