helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.9.1
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true

resources:
  - ./0-cluster-issuer.yaml
