#!/bin/bash

#edit image versions here
export PGO_VERSION="ubi8-5.2.1-0"
export POSTGRES_13_VERSION="ubi8-13.8"
export POSTGRES_13_VERSION_SUFFIX="1"
export POSTGRES_14_VERSION="ubi8-14.5"
export POSTGRES_14_VERSION_SUFFIX="1"
export POSTGRES_GIS_3_0="3.0"
export POSTGRES_GIS_3_1="3.1"
export POSTGRES_GIS_3_2="3.2"
export PGBACKREST_VERSION="ubi8-2.40-1"
export PGADMIN_VERSION="ubi8-4.30-4"
export PGBOUNCER_VERSION="ubi8-1.17-1"

docker pull "registry.developers.crunchydata.com/crunchydata/postgres-operator:$PGO_VERSION"
docker pull "registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade:$PGO_VERSION"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:$POSTGRES_13_VERSION-$POSTGRES_13_VERSION_SUFFIX"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_0-$POSTGRES_13_VERSION_SUFFIX"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_1-$POSTGRES_13_VERSION_SUFFIX"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:$POSTGRES_14_VERSION-$POSTGRES_14_VERSION_SUFFIX"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_1-$POSTGRES_14_VERSION_SUFFIX"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_2-$POSTGRES_14_VERSION_SUFFIX"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:$PGBACKREST_VERSION"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:$PGO_VERSION"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:$PGADMIN_VERSION"
docker pull "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:$PGBOUNCER_VERSION"

docker tag "registry.developers.crunchydata.com/crunchydata/postgres-operator:$PGO_VERSION"                                                               "eu.gcr.io/compelling-cat-212513/crunchydata/postgres-operator:$PGO_VERSION"
docker tag "registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade:$PGO_VERSION"                                                       "eu.gcr.io/compelling-cat-212513/crunchydata/postgres-operator-upgrade:$PGO_VERSION"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:$POSTGRES_13_VERSION-$POSTGRES_13_VERSION_SUFFIX"                            "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres:$POSTGRES_13_VERSION-$POSTGRES_13_VERSION_SUFFIX"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_0-$POSTGRES_13_VERSION_SUFFIX"      "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_0-$POSTGRES_13_VERSION_SUFFIX"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_1-$POSTGRES_13_VERSION_SUFFIX"      "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_1-$POSTGRES_13_VERSION_SUFFIX"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:$POSTGRES_14_VERSION-$POSTGRES_14_VERSION_SUFFIX"                            "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres:$POSTGRES_14_VERSION-$POSTGRES_14_VERSION_SUFFIX"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_1-$POSTGRES_14_VERSION_SUFFIX"      "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_1-$POSTGRES_14_VERSION_SUFFIX"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_2-$POSTGRES_14_VERSION_SUFFIX"      "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_2-$POSTGRES_14_VERSION_SUFFIX"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:$PGBACKREST_VERSION"                                                       "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgbackrest:$PGBACKREST_VERSION"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:$PGO_VERSION"                                                       "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-exporter:$PGO_VERSION"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:$PGADMIN_VERSION"                                                            "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgadmin4:$PGADMIN_VERSION"
docker tag "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:$PGBOUNCER_VERSION"                                                         "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgbouncer:$PGBOUNCER_VERSION"

docker push "eu.gcr.io/compelling-cat-212513/crunchydata/postgres-operator:$PGO_VERSION"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/postgres-operator-upgrade:$PGO_VERSION"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres:$POSTGRES_13_VERSION"-1                      
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_0-1"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_13_VERSION-$POSTGRES_GIS_3_1-1"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres:$POSTGRES_14_VERSION-1"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_1-1"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-gis:$POSTGRES_14_VERSION-$POSTGRES_GIS_3_2-1"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgbackrest:$PGBACKREST_VERSION"                       
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-postgres-exporter:$PGO_VERSION"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgadmin4:$PGADMIN_VERSION"
docker push "eu.gcr.io/compelling-cat-212513/crunchydata/crunchy-pgbouncer:$PGBOUNCER_VERSION"                         